### ISSUE TITLE
Use /var/jb/var/mobile

### ISSUE THREAD

**Issue by Teutates** [haxi0/Derootifier#1]
https://github.com/haxi0/Derootifier/blob/46c397dd5c9b4b26dab9fccb8a2304e0bd7bc3e7/Derootifier/repack-rootless.sh#L10

It is discouraged to use /var/mobile for anything on rootless jailbreaks.

**Comment by haxi0** [comment]
on Dopamine private beta, /var/jb rw is blocked and you can’t write anything there. Seems to be the same for beta 8.
