### ISSUE TITLE
can't convert deb file

### ISSUE THREAD

**Issue by darkhorzen** [haxi0/Derootifier#10]
![30CEA93E-DDF3-4162-9630-6E37358A50FE](https://github.com/haxi0/Derootifier/assets/137117442/d162f6f0-3000-4752-ae9b-cef6efff4fcd)
derutifer is installed via trollstore but still an error pops up when converting the deb file and says that it needs to be installed via trollstore, please help
Iphone Xs 15.4.1

**Comment by luminescen** [comment]
Were you able to fix it?
