### ISSUE TITLE
otool: not found

### ISSUE THREAD

**Issue by F-Unction** [haxi0/Derootifier#4]
Where can I find otool for rootless jailbreak?
![747B705A-3F1B-4696-A7AD-818ECF640684](https://user-images.githubusercontent.com/51352133/236599329-7842ced9-3f67-4169-999a-9f2566bb0356.png)

**Comment by SuperTost100** [comment]
How you solved this issue, because I have the same issue…

**Comment by JEmlay** [comment]
> How you solved this issue, because I have the same issue…

It looks like you might be missing the package odcctools from the Procursus repo.
