### ISSUE TITLE
Help (problem with stupid person not issue)

### ISSUE THREAD

**Issue by pazza2234** [haxi0/Derootifier#9]
![7F681BAF-FA90-40FD-AB96-3083CBBC647B](https://github.com/haxi0/Derootifier/assets/81707002/bc70e5f1-7a96-44ef-9a14-0d9042cad396)
![906D53A6-B8C0-4526-B342-2143FF351303](https://github.com/haxi0/Derootifier/assets/81707002/5df41a77-f7d8-4d6f-8a9b-d4a57f1db62b)

Wat. Can you tell me what to do? I have a iPhone XR iOS 15.2.1, and did. like it said and re installed the app.

**Comment by pazza2234** [comment]
I checked sillio can’t find it, also there was a error before that one that tells me to re install

**Comment by JEmlay** [comment]
You have to have the Procursus repo.  https://apt.procurs.us

The first two lines tell you exactly what to install.  file and ldid.

**Comment by pazza2234** [comment]
oh.
